---
##
# Copyright 2020 ETSI
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
##
name: osmclient
base: core18
version: git
summary: A python client for orchestrating OSM
description: |
  A python client for orchestrating Open Source Mano (OSM).

grade: stable

confinement: strict

environment:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

apps:
  osm:
    # command: usr/bin/osm.wrapper
    command: usr/bin/python3 $SNAP/usr/local/bin/osm
    plugs:
      - network
      - home
      - ssh-public-keys
      # - charm
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      MAGIC: $SNAP/usr/share/file/magic.mgc

parts:
  client:
    plugin: dump
    source: .
    build-environment:
      - PATH: "$PATH:$SNAPCRAFT_PART_INSTALL/usr/local/bin"
    build-packages:
      - git
    stage-packages:
      - python3-pip
      - python3-setuptools
      - python3
      - python3-dev
      - python3-pycurl
      - libmagic1
      - zlib1g-dev
    override-build: |
      BRANCH_OR_TAG=`git symbolic-ref -q --short HEAD || git describe --tags --exact-match`
      git clone https://osm.etsi.org/gerrit/osm/IM.git
      cd IM/
      git checkout $BRANCH_OR_TAG
      $SNAPCRAFT_PART_INSTALL/usr/bin/pip3 install .
      cd ../ && rm -rf IM/
      $SNAPCRAFT_PART_INSTALL/usr/bin/pip3 install .
      snapcraftctl build
